### PR TITLE
Added use of stringi, arguments to readHTMLTable, and whitespace

### PR DESCRIPTION
**Pull request by rmsharp**
Added used of strings package. Substituted use of stri_c() instead of
sprintf() for clarity. Added header = TRUE for clarity. Added
stringsAsFactors = FALSE to avoid having to mess with factors. Added
white space between “if” and “for” keywords and their associated right
parenthesis.

### CODE REVIEW

**Comment by rmsharp** [comment]
I think using 
for (year in years) {
instead of 
for (i in 1:length(years)){
would be clearer.

**Comment by dkalisch** [comment]
Sure. I typically think it is easier with i, j, k etc.  - since they are reserved in my brain for counting, but if you think the other way is better, we can change it.
- Dominik

**Comment by dkalisch** [comment]
Mark,

I also wondering, if there is a way to shorten the following loop:

—
for(i in 1:nrow(nfl.df)){
  if(nfl.df$PtsH[i] > nfl.df$PtsA[i]){
    A[as.numeric(nfl.df$Home[i]), as.numeric(nfl.df$Away[i])] <- 1
  } else if(nfl.df$PtsH[i] < nfl.df$PtsA[i]){
    A[as.numeric(nfl.df$Away[i]), as.numeric(nfl.df$Home[i])] <- 1
  } else {
    A[as.numeric(nfl.df$Home[i]), as.numeric(nfl.df$Away[i])] <- 0.5
    A[as.numeric(nfl.df$Away[i]), as.numeric(nfl.df$Home[i])] <- 0.5
  }
}
—

A friend of mine uses in Matlab this function: 

---
GP = Games; % Legacy (GamesPlayed for short)
N = size(TeamsID,1); %Number of teams

% Create an Incidence Matrix Using Sparse Matrix
T = heaviside(GP.Week-2.5)+1;


Incidence_HomeWins = sparse(GP.HomeID, GP.AwayID, GP.HomeScore .*T, N, N);
Incidence_AwayWins = sparse(GP.AwayID, GP.HomeID, GP.AwayScore .*T, N, N);
IncidenceWL = Incidence_HomeWins + Incidence_AwayWins;
IncidenceWL = full(IncidenceWL)
—

However, if I try this:

—
#### Not working
##library(Matrix)
##
##hs <- Heaviside(nfl.df$Week-2.5) + 1
##
##in.home.w <- sparseMatrix(i = as.numeric(nfl.df$Home),
##                          j = as.numeric(nfl.df$Away),
##                          x = (nfl.df$PtsH %*% hs),
##                          dims = c(nlevels(nfl.df$Home), nlevels(nfl.df$Home)))
##in.away.w <- sparseMatrix(i = as.numeric(nfl.df$Home),
##                          j = as.numeric(nfl.df$Away),
##                          x = (nfl.df$PtsA %*% hs),
##                          dims = c(nlevels(nfl.df$Home), nlevels(nfl.df$Home)))
##
##in.home.w + in.away.w
####
—

it doesn’t work. Do you have any suggestions or ideas? I have attached the script and data object for you.

- Dominik

**Comment by rmsharp** [comment]
I do not know how to find the data object you referred to.
\## Without looking at what you tried. 
\## You can remove the loop entirely and use the vector nature of R objects.
\## I am not sure what is being done with A or how it was made. 
\## I suspect that the use of as.numeric() function could be avoided with 
\## different design. 
\## I am using "greater", "less", and "equal" simply to make it easier for you
\## to read. They are simply logical vectors that have TRUE when the relational
\## operatoration resulted in TRUE. Thus, only those elements in the 
\## nfl.df$Home vector that correspond to the TRUEs are present in the result.
\## Thus,
\## > set.seed(1)
\## > normals <- rnorm(5, 0, 1)
\## > normals
\## [1] -0.6264538  0.1836433 -0.8356286  1.5952808  0.3295078
\## > normals[normals > 0]
\## [1] 0.1836433 1.5952808 0.3295078

greater <- nfl.df$PtsH > nfl.df$PtsA
less <- nfl.df$PtsH < nfl.df$PtsA
equal <- nfl.df$PtsH == nfl.df$PtsA
A[as.numeric(nfl.df$Home[greater]), as.numeric(nfl.df$Away[greater])] <- 1
A[as.numeric(nfl.df$Home[less]), as.numeric(nfl.df$Away[less])] <- 1
A[as.numeric(nfl.df$Home[equal]), as.numeric(nfl.df$Away[equal])] <- 1
\## The last three lines are equivalent to the next six 
A[as.numeric(nfl.df$Home[nfl.df$PtsH > nfl.df$PtsA]), 
  as.numeric(nfl.df$Away[nfl.df$PtsH > nfl.df$PtsA])] <- 1
A[as.numeric(nfl.df$Home[nfl.df$PtsH < nfl.df$PtsA]), 
  as.numeric(nfl.df$Away[nfl.df$PtsH < nfl.df$PtsA])] <- 1
A[as.numeric(nfl.df$Home[nfl.df$PtsH == nfl.df$PtsA]), 
  as.numeric(nfl.df$Away[nfl.df$PtsH == nfl.df$PtsA])] <- 1
`

**Comment by rmsharp** [comment]
Much of importData.R is in HarvestProFootballResults.R except the name of the dataframes nfl.df and games.df. Have you considered using a common file to source into both? I am hesitant to make that change now since we could wait and do that in the class just before we turn the common file into a function.

**Comment by dkalisch** [comment]
Yes, you are right. The difference is, that HarvestProFootballResults.R uses the data from the pro-football webpage, where as importData.R uses the Excel file in the data folder. The structure is a bit different…

**Pull request merged**
